import React, { useState } from "react";
import styled from "styled-components";

const Faq = () => {
    const [faqShow, setFaqShow] = useState(1);
    const [togleFaq1 , setToggleFaq1] = useState(false)
    const [togleFaq2 , setToggleFaq2] = useState(false)
    const [togleFaq3 , setToggleFaq3] = useState(false)
    const [togleFaq4 , setToggleFaq4] = useState(false)
    const [togleFaq5 , setToggleFaq5] = useState(false)
    const [togleFaq6 , setToggleFaq6] = useState(false)
    const [togleFaq7 , setToggleFaq7] = useState(false)
    return (
        <FaqMain id="faq" className="container">
            <div className="col-12 col-sm-10 col-md-11 m-auto">
                <h3>FAQ</h3>
                <div class="faq-list">
                    <div className={
                        togleFaq1 ?
                        "open"
                        :""
                    }>
                        <h4 onClick={() => {setFaqShow(1); setToggleFaq1(!togleFaq1)}}
                            data-bs-toggle="collapse"
                            href="#faq-1"
                            role="button"
                            aria-expanded="false"
                            aria-controls="faq-1"
                        >
                            WHEN WILL THE OFFICIAL PRIME APE PLANET LAUNCH TAKE
                            PLACE?
                        </h4>
                        <div class="collapse multi-collapse" id="faq-1">
                            <p>
                                The official Prime Ape Planet launch date is to
                                be announced. The plan is to have them take over
                                the Metaverse by the end of December, 2021.
                                Further updates will be revealed to the
                                exclusive Discord community of early supporters.
                            </p>
                        </div>
                    </div>
                    <div className={
                        togleFaq2 ?
                        "open"
                        :""
                    }>
                        <h4 onClick={() => {setFaqShow(2); setToggleFaq2(!togleFaq2)}}
                            data-bs-toggle="collapse"
                            href="#faq-2"
                            role="button"
                            aria-expanded="false"
                            aria-controls="faq-2"
                        >
                            HOW CAN I JOIN YOU?
                        </h4>
                        <div class="collapse multi-collapse" id="faq-2">
                            <p>
                                Over 100,000 members compete for a White List
                                spot on our Discord. We still have spots left.
                                But they will all be filled by early supporters
                                of the project who are ready to mint once we
                                announce the launch. If you too want to be among
                                the few able to mint their piece of digital art
                                and claim a Prime Ape you can call your own?
                                <a href="#"> Get started here today.</a>
                            </p>
                        </div>
                    </div>
                    <div className={
                        togleFaq3?
                        "open"
                        :""
                    }>
                        <h4 onClick={() => {setFaqShow(3); setToggleFaq3(!togleFaq3)}}
                            data-bs-toggle="collapse"
                            href="#faq-3"
                            role="button"
                            aria-expanded="false"
                            aria-controls="faq-3"
                        >
                            WILL PRIME APE PLANET MAKE A SOUND INVESTMENT?
                        </h4>
                        <div class="collapse multi-collapse" id="faq-3">
                            <p>
                                Look at the buzz generated by over one hundred
                                thousand people all keen on getting their own
                                Prime Apes. Consider the background of our
                                artists. They have each achieved great things in
                                the world of digital art.
                                Then ask yourself - is this team of artists,
                                crypto visionaries and Metaverse icons a team
                                you’d want to be part of? If it is, you’ll be
                                happy to know we’re right there with you for the
                                long haul. Supporting your decision with a
                                helpful community, transparent decision making
                                and regular updates. We all work together to
                                help Prime Apes dominate the NFT market.
                            </p>
                        </div>
                    </div>
                    <div className={
                        togleFaq4 ?
                        "open"
                        :""
                    }>
                        <h4 onClick={() => {setFaqShow(4); setToggleFaq4(!togleFaq4)}}
                            data-bs-toggle="collapse"
                            href="#faq-4"
                            role="button"
                            aria-expanded="false"
                            aria-controls="faq-4"
                        >
                            HOW MANY PRIME APES ARE TAKING OVER THE DIGITAL
                            JUNGLE?
                        </h4>
                        <div class="collapse multi-collapse" id="faq-4">
                            <p>
                                7979. That’s the unique number of Prime Apes our
                                team has committed to creating. By prioritizing
                                art quality over quantity, we make sure you will
                                be happy with the art you mint. As a result, the
                                demand for Prime Apes will soon tower over the
                                supply.
                            </p>
                        </div>
                    </div>
                    <div className={
                        togleFaq5 ?
                        "open"
                        :""
                    }>
                        <h4 onClick={() => {setFaqShow(5); setToggleFaq5(!togleFaq5)}}
                            data-bs-toggle="collapse"
                            href="#faq-5"
                            role="button"
                            aria-expanded="false"
                            aria-controls="faq-5"
                        >
                            CAN I TAKE A SNEAK PEEK AT MY NFTS?
                        </h4>
                        <div class="collapse multi-collapse" id="faq-5">
                            <p>
                                As soon as you mint one and they’re revealed,
                                you can admire the latest addition to your art
                                collection on OpenSea.
                                Until that happens,
                                <a href="#">
                                    join our Discord’s #sneak-peek channel
                                </a>
                                where you can take a look at what we’ve got
                                cookin’ for you.
                            </p>
                        </div>
                    </div>
                    <div className={
                        togleFaq6 ?
                        "open"
                        :""
                    }>
                        <h4 onClick={() => {setFaqShow(6); setToggleFaq6(!togleFaq6)}}
                            data-bs-toggle="collapse"
                            href="#faq-6"
                            role="button"
                            aria-expanded="false"
                            aria-controls="faq-6"
                        >
                            WHAT BLOCKCHAIN IS THE PROJECT HOSTED ON?
                        </h4>
                        <div class="collapse multi-collapse" id="faq-6">
                            <p>
                                Prime Ape Planet is on the Ethereum Blockchain.
                            </p>
                        </div>
                    </div>
                    <div className={
                        togleFaq7 ?
                        "open"
                        :""
                    }>
                        <h4 onClick={() => {setFaqShow(7); setToggleFaq7(!togleFaq7)}}
                            data-bs-toggle="collapse"
                            href="#faq-7"
                            role="button"
                            aria-expanded="false"
                            aria-controls="faq-7"
                        >
                            DO PRIME APES HAVE ANY UTILITY?
                        </h4>
                        <div class="collapse multi-collapse" id="faq-7">
                            <p>
                                Yes! Prime Ape Planet is one of the only
                                projects in the NFT space that offer a wide
                                array of utilities.
                                Prime Apes will get to partake in exclusive
                                real-life events. They’ll help us make donations
                                to charity that protects Prime Apes in tropical
                                rainforests. AND all the Prime Ape models are
                                equipped to be used in movies, games and
                                meet-ups in the Metaverse.
                                More will be revealed as the Prime Apes march
                                ahead on the Roadmap.
                            </p>
                        </div>
                    </div>
                </div>
                <div className={
                    faqShow === 1 ?
                    "open"
                    :""
                }>
                    <h5>OK, ENOUGH… I CAN’T WAIT TO GET MYSELF A PRIME APE!</h5>
                    <p className="border-none">
                        Once you’re ready to embark on this journey to secure
                        your own piece of iconic digital art,
                        <a href="#">
                            
                            head over to the Official Discord channel.
                        </a>
                        If you’re reading this before the launch, you’ll still
                        have a chance to get your hands on a rare Prime Ape.
                    </p>
                </div>
            </div>
        </FaqMain>
    );
};

export default Faq;

const FaqMain = styled.div`
    padding-top: 80px;
    transition: all 0.5s;
    h3 {
        transition: all 0.5s;

        font-weight: bold;
        line-height: 1.21em;
        font-size: 60px;
        margin: 0 0 22px;
        text-transform: uppercase;
        letter-spacing: 0.135em;
    }
    h4 {
        transition: all 0.5s;
        font-size: 19px;
        letter-spacing: 0.04em;
        cursor: pointer;
        position: relative;
        margin: 0;
        padding: 26px 40px 26px 0;
        ::before {
            content: "";
            position: absolute;
            top: 50%;
            right: 22px;
            width: 3px;
            height: 24px;
            background: #0d5b95;
            box-shadow: 0px 4px 6px #000000;
            transform: translate(0, -50%);
            transition: all 0.4s ease-in-out;
        }
        ::after {
            content: "";
            position: absolute;
            top: 50%;
            right: 12px;
            width: 24px;
            height: 3px;
            background: #0d5b95;
            box-shadow: 0px 4px 6px #000000;
            transform: translate(0, -50%);
            transition: all 0.4s ease-in-out;
        }
        border-bottom: 1px solid #628290;
    }
    p {
        transition: all 0.5s;
        font-weight: normal;
        font-size: 15px;
        line-height: 2.07em;
        letter-spacing: 0.04em;
        color: #f0f0f3;
        border-bottom: 1px solid #628290;
        padding: 30px 0;
    }
    .open h4 {
        ::before {
            opacity: 0 !important;
        }
    }

    .open h4::after {
        background: #ffffff !important;
    }

    h5 {
        font-size: 24px;
        margin: 0 0 20px 0;
        padding: 0;
        font-weight: bold;
        line-height: 1.21em;
        margin-top: 50px;
        margin-bottom: 50px;
    }
    a {
        color: #60cfff;
        font-weight: bold;
    }
    .border-none {
        border-bottom: none;
    }
    @media (max-width:1300px) {
        padding-left: 30px;
        h3 {
            font-size: 46px;
        }
        h4{
            font-size: 17px;
    padding: 20px 40px 20px 0;
        }
        p {
            font-size: 14px;
        }
        
    }
    @media (max-width:992px) {
        h3 {
            font-size: 46px;
        }
        h4 {
            font-size: 14px;
        }
        p {
            font-size: 12px;
        }
        h5 {
            font-size: 20px !important;
            margin-top: 40px;
        margin-bottom: 0px;

        }
    }
    @media (max-width:768px) {
        h3 {
            font-size: 30px;
        }
        h4 {
            font-size: 14px;
    padding: 16px 52px 16px 0;
        }
        h5 {
            font-size: 18px !important;
            margin-top: 30px;

        }
    }

`;
